name: "release"

on:
  push:
    branches: 
      - main

jobs:
  pre-release:
    name: "release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "checkout repo"
        uses: "actions/checkout@v2"
      - name: "setup go"
        uses: "actions/setup-go@v2"
        with:
          go-version: '^1.16.7'
      - name: "log go version"
        run: |
          go version
      - name: "build"
        run: |
          make all
      - name: "release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "grifpkg.com/install"
          files: |
            ./target/*
